# Generated by Django 6.0 on 2025-12-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='gif_file',
            field=models.FileField(blank=True, help_text='Загрузи свой GIF файл', null=True, upload_to='exercises/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='gif_url',
            field=models.URLField(blank=True, help_text='Или укажи ссылку на GIF'),
        ),
    ]
