# Generated by Django 6.0 on 2025-12-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutday',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='workoutday',
            name='category',
        ),
        migrations.AddField(
            model_name='workoutday',
            name='name',
            field=models.CharField(blank=True, help_text='Например: Грудь + Бицепс', max_length=200),
        ),
        migrations.AddField(
            model_name='workoutday',
            name='notes',
            field=models.TextField(blank=True, help_text='Заметки о тренировке'),
        ),
    ]
