# Generated by Django 6.0 on 2025-12-30 09:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_workoutday_options_remove_workoutday_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutday',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата тренировки'),
        ),
    ]
