# Generated by Django 6.0 on 2025-12-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_gif_file_alter_exercise_gif_url'),
        ('workouts', '0003_alter_workoutday_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutday',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Выберите категории упражнений', related_name='workouts', to='exercises.exercisecategory'),
        ),
        migrations.AlterField(
            model_name='workoutday',
            name='name',
            field=models.CharField(blank=True, help_text='Опциональное название', max_length=200),
        ),
    ]
