# Generated by Django 6.0 on 2025-12-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_workoutday_categories_alter_workoutday_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='weights',
            field=models.JSONField(blank=True, help_text='Массив весов для каждого подхода', null=True),
        ),
    ]
