# Generated by Django 6.0 on 2025-12-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_workoutday_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutexercise',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='dropset_weights',
            field=models.JSONField(blank=True, help_text='Массив весов для дроп-сетов: каждый подход содержит массив весов', null=True),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='exercise_type',
            field=models.CharField(choices=[('NORMAL', 'Обычное'), ('DROPSET', 'Дроп-сет'), ('SUPERSET', 'Суперсет')], default='NORMAL', help_text='Тип упражнения', max_length=10),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок выполнения упражнения в тренировке'),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='superset_group',
            field=models.PositiveIntegerField(blank=True, help_text='Номер группы для суперсета (упражнения с одинаковым номером = один суперсет)', null=True),
        ),
    ]
